# Generated by Django 4.2.10 on 2024-08-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_notes_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Task',
            new_name='task',
        ),
    ]
