# Generated by Django 4.2.10 on 2024-08-22 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_task_notes_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_notes', to='books.task'),
        ),
    ]
