# Generated by Django 4.2.10 on 2024-08-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_notes_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pagesRead',
            field=models.IntegerField(default=0),
        ),
    ]
