# Generated by Django 4.2.10 on 2024-08-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_pagesread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pageNumber',
            new_name='numberPages',
        ),
    ]
