# Generated by Django 4.2.10 on 2024-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverUrl',
            field=models.CharField(default='https://via.placeholder.com/150', max_length=500),
        ),
    ]
