# Generated by Django 4.2.10 on 2024-08-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_coverurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_notes', to='books.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numberPages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
