# Generated by Django 4.2.10 on 2024-08-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_notes_book_alter_book_numberpages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverUrl',
            field=models.CharField(blank=True, default='https://via.placeholder.com/150', max_length=500),
        ),
    ]
