# Generated by Django 4.2.10 on 2024-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_coverurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverUrl',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
